import React, { useRef, useEffect, useState } from 'react';
import Evolution from './Evolution';
import TextContent from './TextContent';
import BasicBars from './BarChart';

import { motion } from 'framer-motion';
import { useActiveLink } from './ActiveLinkContext';

import '../style/chart.css';

const ChartContainer = () => {
  const ref = useRef(null);
  const { setActiveLink } = useActiveLink();

  useEffect(() => {
    if (!ref.current) {
      return;
    }

    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveLink('evolution');
          }
        });
      },
      { rootMargin: '0px', threshold: 0.4 }
    );

    observer.observe(ref.current);

    return () => {
      observer.disconnect();
    };
  }, [setActiveLink]);

  const text =
    "At this point, you might be thinking that tennis is a highly polluting sport, and you may not be entirely wrong. However, it is important to put things back into perspective and compare tennis against other major sports. On the right, the histogram sows the emissions of five of the world's most watched sports. Note that the graph entries are calculated by summing the emissions of the top 100 performers in each sport. This graph is unequivocal: tennis is a way less polluting sport than its peers. While other sports generally require more people moving around (team members or crew), it is clear tennis has a relatively reasonable carbon footprint.";
  const test =
    "An ATP season comprises numerous tournaments scattered across the globe. On average, an ATP tournament hosts between 50 and 200 players. The carbon emissions from the players' air travel throughout the season are substantial.\n\n \
  On the left, you can see the median CO2 emissions for the top 100 tennis players, with the median positioned around 21 tons of CO2 per player. However, in 2020, due to COVID-19, this figure dropped to 14 tons because many tournaments were canceled.\n \
  Note: These figures are likely an underestimation, as they do not account for the emissions generated by players traveling back to their homes.";
  return (
    <div>
      <h1 className='chart-title fancy' id='evolution' ref={ref}>
        Evolution & Comparison
      </h1>
      <p className='chart-description'>
        In this section, we delve into the historical analysis of CO2 emissions
        generated by the top 100 ATP tennis players over the past 20 years. This
        helps to understand the trends and changes in the environmental impact
        of professional tennis.
        <br />
        <br />
        Additionally, we provide a comparative analysis of the ATP’s
        environmental footprint against other major international sports leagues
        like the NFL, NBA, and MLS. This comparison offers valuable context,
        highlighting how tennis measures up in terms of travel-related emissions
        within the broader sports industry.
      </p>
      <div className='chart-container'>
        <motion.div
          className='chart'
          initial={{ x: 0 }}
          whileInView={{ x: 0 }}
          transition={{ delay: 0.1, ease: 'easeIn' }}
          viewport={{ once: true, amount: 0.4 }}>
          <Evolution />
        </motion.div>
        <TextContent text={test} offset={0} />
      </div>
      <div style={{ marginTop: '3em' }}></div>
      <div className='chart-container'>
        <TextContent text={text} offset={0} />

        <motion.div
          className='chart'
          initial={{ x: 0 }}
          whileInView={{ x: 0 }}
          transition={{ delay: 0.1, ease: 'easeIn' }}
          viewport={{ once: true, amount: 0.3 }}>
          <BasicBars />
        </motion.div>
      </div>
    </div>
  );
};

export default ChartContainer;
