import React from "react";
import "../style/intro.css";
import "../style/home.css";

const Introduction = () => {
  return (
    <div className="intro" id="intro">
      <p className="intro-text">
        Welcome to <span className="welcomeText">GreenAce</span>, your
        comprehensive resource for understanding the environmental impact of
        professional tennis tours. Our project visualizes the CO2 emissions
        generated by player movements throughout an ATP tennis season, offering
        dynamic and interactive tools to explore these impacts. Dive into our
        visualizations to see the historical trends, track seasonal journeys,
        compare tennis with other sports, and discover the top polluters. Join
        us in promoting sustainability in tennis by making informed,
        eco-friendly decisions.
        <br></br>
        <br></br>
        Explore our site to learn more and see how you can contribute to a{" "}
        <span
          style={{ fontWeight: "bold", color: "#007a00", fontStyle: "italic" }}
        >
          greener
        </span>{" "}
        future in sports.
      </p>
    </div>
  );
};

export default Introduction;
